import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../../app/localization.dart';
import '../../../core/widgets/states.dart';
import '../../auth/presentation/auth_controller.dart';
import '../../courses/data/learning_repository.dart';
import '../../courses/domain/course.dart';
import '../../common/data/student_repository.dart';

final learningRepositoryProvider = Provider((ref) => LearningRepository(ref.read(apiClientProvider)));
final studentRepositoryProvider = Provider((ref) => StudentRepository(ref.read(apiClientProvider)));
final paidCoursesProvider = FutureProvider((ref) => ref.read(learningRepositoryProvider).myCourses());
final achievementsProvider = FutureProvider((ref) => ref.read(studentRepositoryProvider).achievements());

class MainShell extends StatelessWidget {
  const MainShell({super.key, required this.child}); final Widget child;
  static const destinations = [('/home', Icons.home_outlined, 'Home'), ('/learn', Icons.menu_book_outlined, 'Learn'), ('/careers', Icons.work_outline, 'Careers'), ('/profile', Icons.person_outline, 'Profile')];
  @override Widget build(BuildContext context) { final location = GoRouterState.of(context).uri.path; var selected = destinations.indexWhere((e) => location.startsWith(e.$1)); if (selected < 0) selected = 0; return Scaffold(body: child, bottomNavigationBar: NavigationBar(selectedIndex: selected, onDestinationSelected: (i) => context.go(destinations[i].$1), destinations: destinations.map((d) => NavigationDestination(icon: Icon(d.$2), label: d.$3)).toList())); }
}

class HomeScreen extends ConsumerWidget { const HomeScreen({super.key});
  @override Widget build(BuildContext context, WidgetRef ref) { final user = ref.watch(authControllerProvider).user; final paid = ref.watch(paidCoursesProvider); final enrolled = paid.valueOrNull ?? const <String>[]; return Scaffold(appBar: AppBar(title: Text(context.tr('CodePath Learning', 'कोडपाथ लर्निंग')), actions: [IconButton(tooltip: context.tr('Switch language', 'भाषा बदलें'), onPressed: () { final current = ref.read(localeProvider); ref.read(localeProvider.notifier).set(Locale(current.languageCode == 'en' ? 'hi' : 'en')); }, icon: const Icon(Icons.language))]), body: RefreshIndicator(onRefresh: () => ref.refresh(paidCoursesProvider.future), child: ListView(padding: const EdgeInsets.all(18), children: [
    Text(context.tr('Good to see you,', 'आपका स्वागत है,'), style: Theme.of(context).textTheme.titleMedium), Text(user?.name.split(' ').first ?? context.tr('Student', 'विद्यार्थी'), style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.w900)), const SizedBox(height: 20),
    _HeroCard(enrolled: enrolled), const SizedBox(height: 24), Text(context.tr('Quick access', 'त्वरित पहुँच'), style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold)), const SizedBox(height: 12),
    GridView.count(shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), crossAxisCount: 2, childAspectRatio: 1.45, mainAxisSpacing: 12, crossAxisSpacing: 12, children: [
      _Quick(Icons.workspace_premium_outlined, context.tr('Certificates', 'प्रमाणपत्र'), () => context.push('/certificates')),
      _Quick(Icons.support_agent, context.tr('Mentorship', 'मेंटरशिप'), () => context.push('/mentorship')),
      _Quick(Icons.work_outline, context.tr('Career guide', 'करियर गाइड'), () => context.go('/careers')),
      _Quick(Icons.emoji_events_outlined, context.tr('Achievements', 'उपलब्धियाँ'), () => context.push('/achievements')),
    ]), const SizedBox(height: 24), Text(context.tr('Explore courses', 'कोर्स देखें'), style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold)), const SizedBox(height: 12), ...courses.take(3).map((c) => CourseCard(course: c, enrolled: enrolled.contains(c.slug))),
  ]))); }
}
class _HeroCard extends StatelessWidget { const _HeroCard({required this.enrolled}); final List<String> enrolled; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(22), decoration: BoxDecoration(gradient: const LinearGradient(colors: [Color(0xFF4338CA), Color(0xFF7C3AED)]), borderRadius: BorderRadius.circular(24)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Icon(Icons.auto_stories, color: Colors.white, size: 34), const SizedBox(height: 20), Text(enrolled.isEmpty ? context.tr('Start practical learning', 'व्यावहारिक सीखना शुरू करें') : context.tr('Continue learning', 'सीखना जारी रखें'), style: Theme.of(context).textTheme.titleLarge?.copyWith(color: Colors.white, fontWeight: FontWeight.bold)), const SizedBox(height: 7), Text(enrolled.isEmpty ? context.tr('Explore beginner-friendly courses and build real projects.', 'शुरुआती कोर्स देखें और वास्तविक प्रोजेक्ट बनाएँ।') : context.tr('${enrolled.length} course resources are available.', '${enrolled.length} कोर्स संसाधन उपलब्ध हैं।'), style: const TextStyle(color: Colors.white70)), const SizedBox(height: 18), FilledButton.tonal(onPressed: () => context.go('/learn'), child: Text(context.tr('Open learning', 'लर्निंग खोलें')))])); }
class _Quick extends StatelessWidget { const _Quick(this.icon, this.label, this.tap); final IconData icon; final String label; final VoidCallback tap; @override Widget build(BuildContext context) => Card(child: InkWell(borderRadius: BorderRadius.circular(20), onTap: tap, child: Padding(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Icon(icon, color: Theme.of(context).colorScheme.primary), const SizedBox(height: 8), Text(label, style: const TextStyle(fontWeight: FontWeight.w700))])))); }

class LearnScreen extends ConsumerWidget { const LearnScreen({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { final paid = ref.watch(paidCoursesProvider); return Scaffold(appBar: AppBar(title: Text(context.tr('Learn', 'सीखें'))), body: paid.when(loading: () => const Center(child: CircularProgressIndicator()), error: (e, _) => ErrorView(message: e.toString(), onRetry: () => ref.invalidate(paidCoursesProvider)), data: (ids) => ListView(padding: const EdgeInsets.all(18), children: [if (ids.isEmpty) EmptyView(icon: Icons.school_outlined, title: context.tr('No active courses', 'कोई सक्रिय कोर्स नहीं'), message: context.tr('Explore courses to begin your learning journey.', 'सीखना शुरू करने के लिए कोर्स देखें।')) else ...courses.where((c) => ids.contains(c.slug)).map((c) => CourseCard(course: c, enrolled: true)), const SizedBox(height: 22), Text(context.tr('All courses', 'सभी कोर्स'), style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold)), const SizedBox(height: 10), ...courses.map((c) => CourseCard(course: c, enrolled: ids.contains(c.slug)))]))); }
}
class CourseCard extends StatelessWidget { const CourseCard({super.key, required this.course, required this.enrolled}); final Course course; final bool enrolled; @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.only(bottom: 12), child: Card(child: InkWell(borderRadius: BorderRadius.circular(20), onTap: () => context.push('/course/${course.slug}'), child: Padding(padding: const EdgeInsets.all(18), child: Row(children: [CircleAvatar(child: Text(course.title.substring(0, 1))), const SizedBox(width: 14), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(course.title, style: const TextStyle(fontWeight: FontWeight.w800, fontSize: 16)), const SizedBox(height: 5), Text('${course.duration} • ${course.category}', style: Theme.of(context).textTheme.bodySmall), if (enrolled) Padding(padding: const EdgeInsets.only(top: 7), child: Text(context.tr('Available', 'उपलब्ध'), style: TextStyle(color: Theme.of(context).colorScheme.primary, fontWeight: FontWeight.bold))) ])), const Icon(Icons.chevron_right)]))))); }

class CourseDetailScreen extends ConsumerWidget { const CourseDetailScreen({super.key, required this.slug}); final String slug; @override Widget build(BuildContext context, WidgetRef ref) { final course = courses.where((c) => c.slug == slug).firstOrNull; if (course == null) return Scaffold(appBar: AppBar(), body: const EmptyView(icon: Icons.search_off, title: 'Course not found', message: 'This course is unavailable.')); final enrolled = ref.watch(paidCoursesProvider).valueOrNull?.contains(slug) ?? false; return Scaffold(appBar: AppBar(title: Text(course.title)), body: ListView(padding: const EdgeInsets.all(20), children: [Text(course.title, style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.w900)), const SizedBox(height: 8), Text('${course.duration} • ${course.category} • Beginner'), const SizedBox(height: 18), Text(course.description, style: Theme.of(context).textTheme.bodyLarge), const SizedBox(height: 24), Text(context.tr('Syllabus', 'पाठ्यक्रम'), style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold)), const SizedBox(height: 10), ...course.lessons.indexed.map((e) => Card(child: ListTile(leading: CircleAvatar(radius: 17, child: Text('${e.$1 + 1}')), title: Text(e.$2.title), subtitle: Text(e.$2.description))), const SizedBox(height: 22), if (enrolled) ...[ElevatedButton.icon(onPressed: () => _openResource(context, ref, 'classroom'), icon: const Icon(Icons.open_in_new), label: Text(context.tr('Open authorized classroom', 'अधिकृत क्लासरूम खोलें'))), OutlinedButton.icon(onPressed: () => _openResource(context, ref, 'whatsapp'), icon: const Icon(Icons.chat_outlined), label: Text(context.tr('Student support', 'विद्यार्थी सहायता')))] else ElevatedButton(onPressed: () => launchUrl(Uri.parse('https://www.codepathlearning.co.in/register'), mode: LaunchMode.externalApplication), child: Text(context.tr('Register on secure website', 'सुरक्षित वेबसाइट पर रजिस्टर करें')))])); }
  Future<void> _openResource(BuildContext context, WidgetRef ref, String resource) async { try { final uri = await ref.read(learningRepositoryProvider).resource(resource); await launchUrl(uri, mode: LaunchMode.externalApplication); } catch (e) { if (context.mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.toString()))); } }
}
