import { useEffect, useState } from "react";
import { API_URL } from "../config/api";
import "../styles/msme.css";

const fallback = { enterpriseName: "CODEPATH LEARNING", udyamRegistrationNumber: "UDYAM-MP-22-0041513", enterpriseType: "Micro", majorActivity: "Services", businessCategory: "OBC", registrationDate: "18/07/2026", incorporationDate: "13/07/2026", unitName: "CodePath Learning – Online Training Unit", nic: { twoDigit: "85 - Education", fourDigit: "8549 - Other education n.e.c.", fiveDigit: "85499 - Other educational services n.e.c.", activity: "Services" }, certificateUrl: "/documents/udyam-msme-certificate.pdf", qrUrl: "/documents/udyam-msme-qr.png" };

export default function Msme() {
  const [details, setDetails] = useState(fallback);
  useEffect(() => { fetch(`${API_URL}/msme`).then((res) => res.ok ? res.json() : null).then((data) => data?.success && setDetails(data)).catch(() => {}); }, []);
  const rows = [["Enterprise Name", details.enterpriseName], ["Udyam Registration Number", details.udyamRegistrationNumber], ["Enterprise Type", details.enterpriseType], ["Major Activity", details.majorActivity], ["Business Category", details.businessCategory], ["Registration Date", details.registrationDate], ["Incorporation Date", details.incorporationDate], ["Unit", details.unitName], ["NIC 2 Digit", details.nic.twoDigit], ["NIC 4 Digit", details.nic.fourDigit], ["NIC 5 Digit", details.nic.fiveDigit]];
  return <main className="msme-page"><section className="msme-hero"><div className="container"><span className="msme-kicker">OFFICIAL BUSINESS REGISTRATION</span><h1>MSME Registered <span>Enterprise</span></h1><p>Official Udyam registration information for CodePath Learning, presented directly from the provided Government of India certificate.</p></div></section><section className="msme-content"><div className="container msme-layout"><article className="msme-card"><div className="msme-card-heading"><span>UDYAM REGISTRATION</span><strong>{details.udyamRegistrationNumber}</strong></div><div className="msme-facts">{rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</div><div className="msme-actions"><a href={details.certificateUrl} target="_blank" rel="noreferrer">View MSME Certificate ↗</a><a href={details.certificateUrl} download>Download Certificate ↓</a></div></article><aside className="msme-qr-card"><span>OFFICIAL MSME QR</span><img src={details.qrUrl} alt="Official Udyam MSME verification QR" /><p>Scan the official QR to verify the registration certificate.</p></aside></div></section></main>;
}
