import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../../../app/localization.dart';

class OnboardingScreen extends StatefulWidget { const OnboardingScreen({super.key}); @override State<OnboardingScreen> createState() => _OnboardingState(); }
class _OnboardingState extends State<OnboardingScreen> { final controller = PageController(); int index = 0;
  Future<void> done() async { await (await SharedPreferences.getInstance()).setBool('onboarding_complete', true); if (mounted) context.go('/login'); }
  @override Widget build(BuildContext context) { final pages = [(Icons.code_rounded, context.tr('Learn programming practically', 'प्रोग्रामिंग व्यावहारिक रूप से सीखें'), context.tr('Beginner-friendly live learning and guided practice.', 'शुरुआती छात्रों के लिए लाइव सीखना और अभ्यास।')), (Icons.rocket_launch_outlined, context.tr('Build real projects', 'वास्तविक प्रोजेक्ट बनाएँ'), context.tr('Turn concepts into portfolio-ready work.', 'अवधारणाओं को पोर्टफोलियो कार्य में बदलें।')), (Icons.trending_up_rounded, context.tr('Grow your career', 'अपना करियर बढ़ाएँ'), context.tr('Use mentorship, certificates and career guides.', 'मेंटरशिप, प्रमाणपत्र और करियर गाइड पाएँ।'))]; return Scaffold(body: SafeArea(child: Column(children: [Align(alignment: Alignment.centerRight, child: TextButton(onPressed: done, child: Text(context.tr('Skip', 'छोड़ें')))), Expanded(child: PageView(controller: controller, onPageChanged: (v) => setState(() => index = v), children: pages.map((p) => Padding(padding: const EdgeInsets.all(32), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [CircleAvatar(radius: 58, child: Icon(p.$1, size: 58)), const SizedBox(height: 32), Text(p.$2, textAlign: TextAlign.center, style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.w800)), const SizedBox(height: 12), Text(p.$3, textAlign: TextAlign.center, style: Theme.of(context).textTheme.bodyLarge)])).toList())), Padding(padding: const EdgeInsets.all(24), child: Column(children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: List.generate(3, (i) => Container(width: i == index ? 24 : 8, height: 8, margin: const EdgeInsets.all(4), decoration: BoxDecoration(color: i == index ? Theme.of(context).colorScheme.primary : Colors.black12, borderRadius: BorderRadius.circular(9))))), const SizedBox(height: 18), ElevatedButton(onPressed: index == 2 ? done : () => controller.nextPage(duration: const Duration(milliseconds: 250), curve: Curves.easeOut), child: Text(index == 2 ? context.tr('Get Started', 'शुरू करें') : context.tr('Next', 'आगे')))]))]))); }
}
