import 'package:flutter/material.dart';
import '../../../app/localization.dart';

class Career { const Career(this.name, this.org, this.qualification, this.age, this.syllabus, this.selection, this.salary); final String name, org, qualification, age, syllabus, selection, salary; }
const careerPaths = [
  Career('DRDO Technical Assistant', 'DRDO', 'Diploma CS/IT where notified', 'As per notification', 'Technical subjects, aptitude and reasoning', 'Written/technical assessment and verification', 'As per DRDO notification'),
  Career('ISRO Technical Assistant', 'ISRO', 'First-class Diploma CS/IT for eligible posts', 'As notified', 'Diploma technical subjects', 'Written test and skill test as notified', 'As per ISRO notification'),
  Career('BEL Technical Assistant', 'Bharat Electronics Ltd.', 'Diploma CS/IT', 'Around 28', 'C, C++, DBMS, networking, Linux and aptitude', 'Written test/interview or skill assessment', 'As per BEL notification'),
  Career('ECIL Technical Assistant', 'ECIL', 'Diploma CS/IT', 'Around 27', 'Programming, OS, DBMS and networking', 'Written test, skill test/interview and verification', 'As per ECIL notification'),
  Career('POWERGRID Diploma Trainee', 'POWERGRID', 'Diploma CS/IT where notified', 'Around 27', 'Diploma syllabus and aptitude', 'Written test and document verification', 'As per POWERGRID notification'),
  Career('RailTel Technical Posts', 'RailTel', 'Diploma CS/IT', '18–30', 'Networking, Linux, computer fundamentals and aptitude', 'Written test and technical assessment', 'As per RailTel notification'),
  Career('RRB Technician', 'Indian Railways', 'Diploma CS/IT for specific notified posts', 'Notification-dependent', 'Maths, science, reasoning and computer awareness', 'CBT, verification and medical/skill requirements', 'As per RRB notification'),
  Career('State Computer Operator', 'State Departments', 'Diploma CS/IT', 'State-wise', 'Computer basics, typing, MS Office and GK', 'Written and typing/skill tests', 'State notification-dependent'),
  Career('e-Governance Technical Assistant', 'State e-Governance Missions', 'Diploma CS/IT', 'State-wise', 'Networking, Linux, Office and internet', 'Written test or technical interview', 'Notification-dependent'),
  Career('Government Polytechnic Lab Assistant', 'State Technical Education', 'Diploma CS/IT', 'State-wise', 'Hardware, software, networking and programming', 'Written and practical/skill test', 'As per state notification'),
];

class CareersScreen extends StatefulWidget { const CareersScreen({super.key}); @override State<CareersScreen> createState() => _CareersState(); }
class _CareersState extends State<CareersScreen> { String query = ''; @override Widget build(BuildContext context) { final items = careerPaths.where((e) => '${e.name} ${e.org}'.toLowerCase().contains(query.toLowerCase())).toList(); return Scaffold(appBar: AppBar(title: Text(context.tr('Diploma government careers', 'डिप्लोमा सरकारी करियर'))), body: ListView(padding: const EdgeInsets.all(18), children: [Container(padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: const Color(0xFF17213D), borderRadius: BorderRadius.circular(20)), child: Text(context.tr('Free informational guide. Eligibility, vacancies, age, salary and rules change—always verify the latest official notification.', 'निःशुल्क जानकारी गाइड। पात्रता, रिक्तियाँ, आयु, वेतन और नियम बदलते हैं—हमेशा नवीनतम आधिकारिक अधिसूचना जाँचें।'), style: const TextStyle(color: Colors.white, height: 1.5))), const SizedBox(height: 16), TextField(onChanged: (v) => setState(() => query = v), decoration: InputDecoration(prefixIcon: const Icon(Icons.search), hintText: context.tr('Search pathways', 'करियर खोजें'))), const SizedBox(height: 16), if (items.isEmpty) const Center(child: Padding(padding: EdgeInsets.all(32), child: Text('No matching pathways'))) else ...items.map((e) => Padding(padding: const EdgeInsets.only(bottom: 12), child: Card(child: ListTile(contentPadding: const EdgeInsets.all(16), title: Text(e.name, style: const TextStyle(fontWeight: FontWeight.w800)), subtitle: Text(e.org), trailing: const Icon(Icons.chevron_right), onTap: () => Navigator.of(context).push(MaterialPageRoute(builder: (_) => CareerDetail(career: e))))))])); }
}
class CareerDetail extends StatelessWidget { const CareerDetail({super.key, required this.career}); final Career career; @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text(career.name)), body: ListView(padding: const EdgeInsets.all(20), children: [Text(career.org, style: TextStyle(color: Theme.of(context).colorScheme.primary, fontWeight: FontWeight.bold)), const SizedBox(height: 12), ...[('Qualification / branches', career.qualification), ('Age limit', career.age), ('Exam syllabus', career.syllabus), ('Selection process', career.selection), ('Salary / stipend', career.salary)].map((e) => Card(child: ListTile(title: Text(e.$1, style: const TextStyle(fontWeight: FontWeight.w700)), subtitle: Padding(padding: const EdgeInsets.only(top: 5), child: Text(e.$2))))), const SizedBox(height: 16), Text(context.tr('This is career awareness, not a vacancy notice or job guarantee. Verify the official organisation notification before applying.', 'यह करियर जानकारी है, भर्ती सूचना या नौकरी की गारंटी नहीं। आवेदन से पहले आधिकारिक अधिसूचना जाँचें।'))])); }

