import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../../app/localization.dart';
import '../../../core/widgets/states.dart';
import '../../auth/presentation/auth_controller.dart';
import '../../courses/domain/course.dart';
import '../../home/presentation/main_shell.dart';

class CertificatesScreen extends ConsumerStatefulWidget { const CertificatesScreen({super.key}); @override ConsumerState<CertificatesScreen> createState() => _CertificatesState(); }
class _CertificatesState extends ConsumerState<CertificatesScreen> { final id = TextEditingController(); Map<String, dynamic>? result; String? error; bool busy = false;
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text(context.tr('Certificates', 'प्रमाणपत्र'))), body: ListView(padding: const EdgeInsets.all(20), children: [Text(context.tr('Verify a certificate', 'प्रमाणपत्र सत्यापित करें'), style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.bold)), const SizedBox(height: 8), Text(context.tr('Enter the genuine Certificate ID issued by CodePath Learning.', 'CodePath Learning द्वारा जारी प्रमाणपत्र आईडी दर्ज करें।')), const SizedBox(height: 18), TextField(controller: id, textCapitalization: TextCapitalization.characters, decoration: const InputDecoration(labelText: 'Certificate ID', prefixIcon: Icon(Icons.verified_outlined))), const SizedBox(height: 12), ElevatedButton(onPressed: busy ? null : verify, child: busy ? const CircularProgressIndicator(color: Colors.white) : Text(context.tr('Verify', 'सत्यापित करें'))), if (error != null) Padding(padding: const EdgeInsets.only(top: 16), child: Text(error!, style: TextStyle(color: Theme.of(context).colorScheme.error))), if (result != null) Padding(padding: const EdgeInsets.only(top: 18), child: Card(child: Padding(padding: const EdgeInsets.all(18), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Row(children: [Icon(Icons.verified, color: Colors.green), SizedBox(width: 8), Text('VALID', style: TextStyle(fontWeight: FontWeight.bold, color: Colors.green))]), const SizedBox(height: 14), Text(result!['studentName']?.toString() ?? '', style: Theme.of(context).textTheme.titleLarge), Text(result!['course']?.toString() ?? ''), Text('ID: ${result!['certificateId']}'), const SizedBox(height: 12), Wrap(spacing: 8, children: [OutlinedButton.icon(onPressed: () => Share.share('Verify ${result!['certificateId']} at https://www.codepathlearning.co.in/verify/${result!['certificateId']}'), icon: const Icon(Icons.share), label: const Text('Share')), if ((result!['certificatePdf'] ?? '').toString().isNotEmpty) OutlinedButton.icon(onPressed: () => launchUrl(Uri.parse(result!['certificatePdf'].toString()), mode: LaunchMode.externalApplication), icon: const Icon(Icons.open_in_new), label: const Text('Open'))])]))))]));
  Future<void> verify() async { if (id.text.trim().isEmpty) return; setState(() { busy = true; error = null; result = null; }); try { result = await ref.read(studentRepositoryProvider).verifyCertificate(id.text); if (result == null) error = 'Certificate is invalid or not found.'; } catch (e) { error = e.toString(); } if (mounted) setState(() => busy = false); }
}

class AchievementsScreen extends ConsumerWidget { const AchievementsScreen({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { final value = ref.watch(achievementsProvider); return Scaffold(appBar: AppBar(title: Text(context.tr('Achievements', 'उपलब्धियाँ'))), body: value.when(loading: () => const Center(child: CircularProgressIndicator()), error: (e, _) => ErrorView(message: e.toString(), onRetry: () => ref.invalidate(achievementsProvider)), data: (items) => items.isEmpty ? EmptyView(icon: Icons.emoji_events_outlined, title: context.tr('No achievements yet', 'अभी कोई उपलब्धि नहीं'), message: context.tr('Published student milestones will appear here.', 'प्रकाशित विद्यार्थी उपलब्धियाँ यहाँ दिखेंगी।')) : ListView.builder(padding: const EdgeInsets.all(16), itemCount: items.length, itemBuilder: (_, i) { final src = items[i]['posterImage']?.toString() ?? ''; return Padding(padding: const EdgeInsets.only(bottom: 14), child: ClipRRect(borderRadius: BorderRadius.circular(18), child: src.startsWith('data:image') ? Image.memory(base64Decode(src.split(',').last), fit: BoxFit.cover, semanticLabel: 'Student achievement') : const SizedBox.shrink())); })))); }
}

class MentorshipScreen extends ConsumerStatefulWidget { const MentorshipScreen({super.key}); @override ConsumerState<MentorshipScreen> createState() => _MentorshipState(); }
class _MentorshipState extends ConsumerState<MentorshipScreen> { final utr = TextEditingController(), notes = TextEditingController(); String topic = 'Career Guidance'; bool busy = false; String? message;
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text(context.tr('Mentorship', 'मेंटरशिप'))), body: ListView(padding: const EdgeInsets.all(20), children: [Text(context.tr('One-to-One Live Mentorship', 'वन-टू-वन लाइव मेंटरशिप'), style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.bold)), const SizedBox(height: 8), Text(context.tr('Available to enrolled students. Manual payment is reviewed by the team before access is unlocked.', 'नामांकित विद्यार्थियों के लिए उपलब्ध। पहुँच मिलने से पहले टीम भुगतान सत्यापित करती है।')), const SizedBox(height: 20), DropdownButtonFormField(value: topic, decoration: InputDecoration(labelText: context.tr('Topic', 'विषय')), items: ['Placement','Internship','Projects','Resume Review','Interview','Career Guidance','Higher Studies'].map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(), onChanged: (v) => setState(() => topic = v!)), const SizedBox(height: 12), TextField(controller: utr, keyboardType: TextInputType.number, maxLength: 12, decoration: InputDecoration(labelText: context.tr('12-digit bank UTR/RRN', '12 अंकों का बैंक UTR/RRN'))), TextField(controller: notes, maxLines: 4, decoration: InputDecoration(labelText: context.tr('Notes (optional)', 'नोट्स (वैकल्पिक)'))), if (message != null) Padding(padding: const EdgeInsets.symmetric(vertical: 12), child: Text(message!)), ElevatedButton(onPressed: busy ? null : submit, child: Text(context.tr('Submit for verification', 'सत्यापन हेतु भेजें')))]));
  Future<void> submit() async { setState(() { busy = true; message = null; }); try { await ref.read(studentRepositoryProvider).bookMentorship({'topic': topic, 'transactionId': utr.text, 'notes': notes.text}); message = 'Request submitted. Access remains locked until payment is verified.'; } catch (e) { message = e.toString(); } if (mounted) setState(() => busy = false); }
}

class FeedbackScreen extends ConsumerStatefulWidget { const FeedbackScreen({super.key}); @override ConsumerState<FeedbackScreen> createState() => _FeedbackState(); }
class _FeedbackState extends ConsumerState<FeedbackScreen> { String course = 'Web Development', recommendation = 'yes'; final liked = TextEditingController(), suggestions = TextEditingController(); final ratings = {'overall':5,'explanation':5,'content':5,'platform':5}; String? message; bool busy = false;
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text(context.tr('Feedback', 'प्रतिक्रिया'))), body: ListView(padding: const EdgeInsets.all(20), children: [DropdownButtonFormField(value: course, decoration: InputDecoration(labelText: context.tr('Course', 'कोर्स')), items: courses.where((e) => ['web-development','python','c-programming','mysql','vibe-coding-ai','ai-tools-projects'].contains(e.slug)).map((e) => DropdownMenuItem(value: e.title, child: Text(e.title))).toList(), onChanged: (v) => setState(() => course = v!)), const SizedBox(height: 14), ...ratings.keys.map((key) => Row(children: [Expanded(child: Text(key[0].toUpperCase() + key.substring(1))), DropdownButton<int>(value: ratings[key], items: List.generate(5, (i) => DropdownMenuItem(value: i + 1, child: Text('${i + 1} ★'))), onChanged: (v) => setState(() => ratings[key] = v!))])), const SizedBox(height: 10), TextField(controller: liked, maxLines: 3, decoration: InputDecoration(labelText: context.tr('What did you like most?', 'आपको सबसे अच्छा क्या लगा?'))), const SizedBox(height: 12), TextField(controller: suggestions, maxLines: 3, decoration: InputDecoration(labelText: context.tr('Suggestions', 'सुझाव'))), const SizedBox(height: 12), SegmentedButton<String>(segments: const [ButtonSegment(value:'yes', label:Text('Yes')), ButtonSegment(value:'maybe', label:Text('Maybe')), ButtonSegment(value:'no', label:Text('No'))], selected: {recommendation}, onSelectionChanged: (v) => setState(() => recommendation = v.first)), if (message != null) Padding(padding: const EdgeInsets.symmetric(vertical: 12), child: Text(message!)), ElevatedButton(onPressed: busy ? null : submit, child: Text(context.tr('Submit feedback', 'प्रतिक्रिया भेजें')))]));
  Future<void> submit() async { setState(() => busy = true); try { await ref.read(studentRepositoryProvider).saveFeedback({'course':course,'ratings':ratings,'recommendation':recommendation,'likedMost':liked.text,'suggestions':suggestions.text}); message = 'Thank you! Your feedback has been saved.'; } catch (e) { message = e.toString(); } if (mounted) setState(() => busy = false); }
}

class ProfileScreen extends ConsumerWidget { const ProfileScreen({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { final user = ref.watch(authControllerProvider).user; return Scaffold(appBar: AppBar(title: Text(context.tr('Profile', 'प्रोफ़ाइल'))), body: ListView(padding: const EdgeInsets.all(18), children: [CircleAvatar(radius: 42, child: Text(user?.name.isNotEmpty == true ? user!.name[0].toUpperCase() : 'S', style: const TextStyle(fontSize: 28))), const SizedBox(height: 12), Center(child: Text(user?.name ?? '', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold))), Center(child: Text(user?.email ?? '')), const SizedBox(height: 22), if ((user?.phone ?? '').isNotEmpty) ListTile(leading: const Icon(Icons.phone_outlined), title: Text(user!.phone)), ListTile(leading: const Icon(Icons.workspace_premium_outlined), title: Text(context.tr('Certificates', 'प्रमाणपत्र')), onTap: () => context.push('/certificates')), ListTile(leading: const Icon(Icons.rate_review_outlined), title: Text(context.tr('Feedback', 'प्रतिक्रिया')), onTap: () => context.push('/feedback')), ListTile(leading: const Icon(Icons.support_agent), title: Text(context.tr('Support', 'सहायता')), subtitle: const Text('codepathlearning@gmail.com'), onTap: () => launchUrl(Uri.parse('mailto:codepathlearning@gmail.com'))), ListTile(leading: const Icon(Icons.info_outline), title: Text(context.tr('About CodePath Learning', 'CodePath Learning के बारे में')), subtitle: const Text('MSME: UDYAM-MP-22-0041513'), onTap: () => launchUrl(Uri.parse('https://www.codepathlearning.co.in/about'), mode: LaunchMode.externalApplication)), ListTile(leading: const Icon(Icons.policy_outlined), title: Text(context.tr('Certificate policy', 'प्रमाणपत्र नीति')), onTap: () => launchUrl(Uri.parse('https://www.codepathlearning.co.in/certificate-policy'), mode: LaunchMode.externalApplication)), const SizedBox(height: 12), OutlinedButton.icon(onPressed: () async { await ref.read(authControllerProvider.notifier).logout(); if (context.mounted) context.go('/login'); }, icon: const Icon(Icons.logout), label: Text(context.tr('Logout', 'लॉग आउट')))])); }
}
